# Generated by Django 4.2 on 2023-06-15 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_profile_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="username",
            new_name="user",
        ),
    ]
