# Generated by Django 4.2 on 2023-06-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_remove_profile_follows"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPredict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.TextField(max_length=150)),
            ],
        ),
    ]
