# Generated by Django 4.2 on 2023-06-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_remove_profile_profile_image_profile_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
    ]
