# Generated by Django 4.2 on 2023-07-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_profile_avatar"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataPredict",
        ),
    ]
