# Generated by Django 4.2 on 2023-07-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_delete_datapredict"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty_name", models.CharField(max_length=200)),
                ("branch_name", models.CharField(max_length=200)),
            ],
        ),
    ]
