# Generated by Django 4.2 on 2023-07-06 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_alter_branch_branch_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="branch_name",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="branch_name",
        ),
        migrations.AddField(
            model_name="branch",
            name="faculty_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.faculty",
            ),
            preserve_default=False,
        ),
    ]
